apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: storage-event
  namespace: user1
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    upload:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /upload
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST
